CREATE TABLE tb_fact_tuberculose(
 hash       TEXT not null,
 nu_idade_n INTEGER,
 cs_sexo    TEXT,
 id_ocupa_n INTEGER,
 cs_gestant INTEGER,
 tp_not     INTEGER,
 cs_raca    INTEGER,
 cs_escol_n INTEGER,
 id_municip INTEGER,
 id_mn_resi INTEGER,
 dt_notific DATE,
 raiox_tora INTEGER,
 teste_tube INTEGER,
 forma      INTEGER,
 sg_uf_at   INTEGER,
 transf     INTEGER,
 uf_transf  INTEGER,
 mun_transf INTEGER,
 hiv        INTEGER,
 test_sensi INTEGER,
 sg_uf_not  INTEGER,
 sg_uf      INTEGER,
 dt_transus DATE,
 tratamento INTEGER,
 agravaids  INTEGER,
 agravalcoo INTEGER,
 agravdiabe INTEGER,
 agravdoenc INTEGER,
 agravoutra INTEGER,
 agravdroga INTEGER,
 agravtabac INTEGER,
 bacilosc_e INTEGER,
 cultura_es INTEGER,
 test_molec INTEGER,
 tratsup_at INTEGER,
 nu_contato INTEGER,
 nu_comu_ex INTEGER,
 ant_retro INTEGER,
 bacilosc_1 INTEGER,
 bacilosc_2 INTEGER,
 bacilosc_3 INTEGER,
 bacilosc_4 INTEGER,
 bacilosc_5 INTEGER,
 bacilosc_6 INTEGER,
 bac_apos_6 INTEGER,
 situa_ence INTEGER,
 dt_inic_tr DATE,
 
 

 PRIMARY KEY (hash),
 FOREIGN KEY (hiv) REFERENCES tb_dim_hiv_tipo (hiv),
 FOREIGN KEY (id_ocupa_n) REFERENCES tb_dim_ocupacao_economica (codigo),
 FOREIGN KEY (cs_raca) REFERENCES tb_dim_raca (id_raca),
 FOREIGN KEY (id_municip) REFERENCES tb_dim_location (codigo_ibge),
 FOREIGN KEY (id_mn_resi) REFERENCES tb_dim_location (codigo_ibge),
 FOREIGN KEY (forma) REFERENCES tb_dim_forma_teste_tuberculose (forma_id),
 FOREIGN KEY (transf) REFERENCES tb_dim_transferido_tipo (transf_id),
 FOREIGN KEY (test_sensi) REFERENCES tb_dim_teste_sensibilidade (test_sensi_id),
 FOREIGN KEY (raiox_tora) REFERENCES tb_dim_raiox (id_raiox),
 FOREIGN KEY (test_molec) REFERENCES tb_dim_teste_molecular (test_molec),
 FOREIGN KEY (tratamento) REFERENCES tb_dim_tipo_entrada (tratamento),
 FOREIGN KEY (cs_escol_n) REFERENCES tb_dim_escolaridade (cs_escol_n),
 FOREIGN KEY (cs_gestant) REFERENCES tb_dim_gestante (cs_gestant),
 FOREIGN KEY (situa_ence) REFERENCES tb_dim_situacao_encerramento (situa_ence)
);

